### PR TITLE
Increase HR -> TPW Hire DAG timeout

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
- https://github.com/cityofaustin/atd-data-tech/issues/17140

## Associated repo
- atd-knack-servces

## Testing

**Steps to test:**
1. Run the DAG locally

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Add note to 1PW secrets moved to API vault and check for duplicates

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
# 🚢 🚢 💯

**Review by Charlie-Henry — APPROVED** [review]
@johnclary this is fine but this should not be taking this much time 😅 we're still working on a couple of bugs with this script so I'll hit pause for the time being

**Comment by johnclary** [comment]
thanks @Charlie-Henry. sounds good. i was wondering if there were some beastly calculated fields or something in the app that were slowing things down...

**Review by chiaberry — APPROVED** [review]

**Comment by Charlie-Henry** [comment]
@johnclary I've discovered what is causing this, it's on the knack-side of things. I think we can merge this in the meantime to get this DAG running again?

**Comment by johnclary** [comment]
👍

**Comment by Charlie-Henry** [comment]
gracias, I can deploy these changes and flip it back on 👍

**Pull request merged**
