### PR TITLE
Update Moving to production section

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues
n/a

I made this small update, and I'm wondering if we should point the [Dev server docs](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/servers/dts-int-data-p01-on-prem-server) to this readme? I know we are still feeling out how all this works, but I like how we decided to keep these details close to the repo.

## Associated repo
n/a

## Testing

**Steps to test:**
None

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [ ] ~Add note to 1PW secrets moved to API vault and check for duplicates~

### CODE REVIEW

**Review by johnclary — APPROVED** [review]
thanks @mddilley!

**Review by chiaberry — APPROVED** [review]
thanks mike!

linking from the docs to here would be helpful, it would remind anyone updating the gitbook docs to also update these

**Review by frankhereford — APPROVED** [review]
These changes are great. Thank you @mddilley!

Nevermind - I had my comment totally backwards about linking. I thought you were asking about README -> internal docs, but it's the other way around. Linking to the README from internal docs is awesome and a huge yes from me.

**Review by roseeichelmann — APPROVED** [review]
Thanks for updating this mike! :rocket:

**Comment by mddilley** [comment]
finally merging this one - thanks y'all!

**Pull request merged**
