### PR TITLE
Remove cr3 download DAG

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/12849

🪓ing the CR3 download DAG. See https://github.com/cityofaustin/atd-vz-data/pull/1262.

## Testing

**Steps to test:**
1. You can test spinning up the local stack if you would like.

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [x] Add note to 1PW secrets moved to API vault and check for duplicates

### CODE REVIEW

**Review by johnclary — APPROVED** [review]
I am sad. 💐 🪦 

Thanks for trying to make this happen @mddilley!

**Review by frankhereford — APPROVED** [review]
I am also bummed! This was so cool. Thanks for nixing this file Mike. We'll find a way in the future!

**Review by chiaberry — APPROVED** [review]
pour one out 🥀

**Comment by mddilley** [comment]
Thanks y'all! 💐 🚀

**Pull request merged**
