### PR TITLE
Increase VZ Socrata DAG timeout

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues
n/a

This ETL is taking longer than expected in Airflow v2 so I'm doubling the timeout. It also received a 500 from Socrata so I added a couple of retries. Open to any other suggestions! This was a really solid ETL in v1 so I'm hoping that this just bad luck this week.

## Testing

**Steps to test:**
1. Not much to test here. The ETL ran successfully - it just took longer than expected.

---
#### Ship list
- [x] Code reviewed 
- [ ] Product manager approved
- [ ] Add note to 1PW secrets moved to API vault and check for duplicates

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
This looks great Mike - and the sibling PR too. Thank you for fixing this so quickly.

**Review by Charlie-Henry — APPROVED** [review]
Socrata 🐌 🚢

**Review by roseeichelmann — APPROVED** [review]
looks good, hopefully all is well after this :crossed_fingers:

**Comment by mddilley** [comment]
Thanks for the speedy reviews, y'all! 🏎️

**Pull request merged**
